// <auto-generated />
using System;
using LovchaFantasy.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LovchaFantasy.Context.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240927115056_fixGame3")]
    partial class fixGame3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Actionn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("actions");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ImageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("clubs");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ImageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("games");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.GameClubs", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "ClubId");

                    b.HasIndex("ClubId");

                    b.ToTable("gameClubs");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.GameWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("gameWeeks");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.GameWeekPlayer", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("GameWeekId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClubId")
                        .HasColumnType("integer");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("PlayerId", "GameWeekId");

                    b.HasIndex("ClubId");

                    b.HasIndex("GameWeekId");

                    b.HasIndex("PositionId");

                    b.ToTable("gameWeekPlayers");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("images");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<bool>("Main")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("leagues");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ImageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("players");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Points", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("ActionnId")
                        .HasColumnType("integer");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.Property<int>("Point")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "ActionnId", "PositionId");

                    b.HasIndex("ActionnId");

                    b.HasIndex("PositionId");

                    b.ToTable("points");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("positions");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.PositionCountRules", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCount")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("positionCountRules");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Rules", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("BenchCount")
                        .HasColumnType("integer");

                    b.Property<int>("GwTransfers")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTransfers")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUserTeams")
                        .HasColumnType("integer");

                    b.Property<int>("OneClubPlayersCount")
                        .HasColumnType("integer");

                    b.Property<double>("StartBalance")
                        .HasColumnType("double precision");

                    b.Property<int>("StartUpDefCount")
                        .HasColumnType("integer");

                    b.Property<int>("StartUpFwdCount")
                        .HasColumnType("integer");

                    b.Property<int>("StartUpGkCount")
                        .HasColumnType("integer");

                    b.Property<int>("StartUpMidCount")
                        .HasColumnType("integer");

                    b.Property<int>("TeamCount")
                        .HasColumnType("integer");

                    b.HasKey("GameId");

                    b.ToTable("rules");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.UserLeagues", b =>
                {
                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<int>("UserTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.HasKey("LeagueId", "UserTeamId", "GameId");

                    b.HasIndex("UserTeamId", "GameId");

                    b.ToTable("userLeagues");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.UserTeam", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "GameId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("userTeam");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.UserTeamBalance", b =>
                {
                    b.Property<int>("UserTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("GameWeekId")
                        .HasColumnType("integer");

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.HasKey("UserTeamId", "GameId", "GameWeekId");

                    b.HasIndex("GameWeekId");

                    b.ToTable("userTeamBalances");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.UserTeamGameWeekPlayer", b =>
                {
                    b.Property<int>("UserTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("GameWeekId")
                        .HasColumnType("integer");

                    b.Property<bool>("Bench")
                        .HasColumnType("boolean");

                    b.Property<bool>("Captain")
                        .HasColumnType("boolean");

                    b.Property<bool>("ViceCaptain")
                        .HasColumnType("boolean");

                    b.HasKey("UserTeamId", "GameId", "PlayerId", "GameWeekId");

                    b.HasIndex("PlayerId", "GameWeekId");

                    b.ToTable("userTeamGameWeekPlayers");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Club", b =>
                {
                    b.HasOne("LovchaFantasy.Models.Fantasy.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Game", b =>
                {
                    b.HasOne("LovchaFantasy.Models.Fantasy.Image", "Image")
                        .WithMany("Games")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.GameClubs", b =>
                {
                    b.HasOne("LovchaFantasy.Models.Fantasy.Club", "Club")
                        .WithMany("GameClubs")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LovchaFantasy.Models.Fantasy.Game", "Game")
                        .WithMany("GameClubs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.GameWeek", b =>
                {
                    b.HasOne("LovchaFantasy.Models.Fantasy.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.GameWeekPlayer", b =>
                {
                    b.HasOne("LovchaFantasy.Models.Fantasy.Club", "Club")
                        .WithMany("GameWeekPlayers")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LovchaFantasy.Models.Fantasy.GameWeek", "GameWeek")
                        .WithMany("GameWeekPlayers")
                        .HasForeignKey("GameWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LovchaFantasy.Models.Fantasy.Player", "Player")
                        .WithMany("GameWeekPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LovchaFantasy.Models.Fantasy.Position", "Position")
                        .WithMany("GameWeekPlayers")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("GameWeek");

                    b.Navigation("Player");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.League", b =>
                {
                    b.HasOne("LovchaFantasy.Models.Fantasy.Game", "Game")
                        .WithMany("Leagues")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Player", b =>
                {
                    b.HasOne("LovchaFantasy.Models.Fantasy.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Points", b =>
                {
                    b.HasOne("LovchaFantasy.Models.Fantasy.Actionn", "Actionn")
                        .WithMany("Points")
                        .HasForeignKey("ActionnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LovchaFantasy.Models.Fantasy.Game", "Game")
                        .WithMany("Points")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LovchaFantasy.Models.Fantasy.Position", "Position")
                        .WithMany("Points")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actionn");

                    b.Navigation("Game");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.PositionCountRules", b =>
                {
                    b.HasOne("LovchaFantasy.Models.Fantasy.Game", "Game")
                        .WithMany("PositionCountRules")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LovchaFantasy.Models.Fantasy.Position", "Position")
                        .WithMany("PositionCountRules")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Rules", b =>
                {
                    b.HasOne("LovchaFantasy.Models.Fantasy.Game", "Game")
                        .WithOne("Rules")
                        .HasForeignKey("LovchaFantasy.Models.Fantasy.Rules", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.UserLeagues", b =>
                {
                    b.HasOne("LovchaFantasy.Models.Fantasy.League", "League")
                        .WithMany("UserLeagues")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LovchaFantasy.Models.Fantasy.UserTeam", "UserTeam")
                        .WithMany("UserLeagues")
                        .HasForeignKey("UserTeamId", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("UserTeam");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.UserTeam", b =>
                {
                    b.HasOne("LovchaFantasy.Models.Fantasy.Game", "Game")
                        .WithMany("UserTeams")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LovchaFantasy.Models.Fantasy.ApplicationUser", "User")
                        .WithMany("UserTeams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.UserTeamBalance", b =>
                {
                    b.HasOne("LovchaFantasy.Models.Fantasy.GameWeek", "GameWeek")
                        .WithMany("UserTeamBalances")
                        .HasForeignKey("GameWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LovchaFantasy.Models.Fantasy.UserTeam", "UserTeam")
                        .WithMany("UserTeamBalances")
                        .HasForeignKey("UserTeamId", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameWeek");

                    b.Navigation("UserTeam");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.UserTeamGameWeekPlayer", b =>
                {
                    b.HasOne("LovchaFantasy.Models.Fantasy.GameWeekPlayer", "GameWeekPlayer")
                        .WithMany("UserTeamGameWeekPlayers")
                        .HasForeignKey("PlayerId", "GameWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LovchaFantasy.Models.Fantasy.UserTeam", "UserTeam")
                        .WithMany("UserTeamGameWeekPlayers")
                        .HasForeignKey("UserTeamId", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameWeekPlayer");

                    b.Navigation("UserTeam");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Actionn", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.ApplicationUser", b =>
                {
                    b.Navigation("UserTeams");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Club", b =>
                {
                    b.Navigation("GameClubs");

                    b.Navigation("GameWeekPlayers");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Game", b =>
                {
                    b.Navigation("GameClubs");

                    b.Navigation("Leagues");

                    b.Navigation("Points");

                    b.Navigation("PositionCountRules");

                    b.Navigation("Rules")
                        .IsRequired();

                    b.Navigation("UserTeams");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.GameWeek", b =>
                {
                    b.Navigation("GameWeekPlayers");

                    b.Navigation("UserTeamBalances");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.GameWeekPlayer", b =>
                {
                    b.Navigation("UserTeamGameWeekPlayers");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Image", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.League", b =>
                {
                    b.Navigation("UserLeagues");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Player", b =>
                {
                    b.Navigation("GameWeekPlayers");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.Position", b =>
                {
                    b.Navigation("GameWeekPlayers");

                    b.Navigation("Points");

                    b.Navigation("PositionCountRules");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Fantasy.UserTeam", b =>
                {
                    b.Navigation("UserLeagues");

                    b.Navigation("UserTeamBalances");

                    b.Navigation("UserTeamGameWeekPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
