// <auto-generated />
using System;
using LovchaFantasy.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LovchaFantasy.Context.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240807124829_AddRules2")]
    partial class AddRules2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LovchaFantasy.Models.Game", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("end")
                        .HasColumnType("date");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("start")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.ToTable("games");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("images");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Rules", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("BenchCount")
                        .HasColumnType("integer");

                    b.Property<int>("GwTransfers")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTransfers")
                        .HasColumnType("integer");

                    b.Property<int>("OneClubPlayersCount")
                        .HasColumnType("integer");

                    b.Property<int>("TeamCount")
                        .HasColumnType("integer");

                    b.Property<bool>("TimePoints")
                        .HasColumnType("boolean");

                    b.HasKey("GameId");

                    b.ToTable("rules");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Rules", b =>
                {
                    b.HasOne("LovchaFantasy.Models.Game", "Game")
                        .WithOne("Rules")
                        .HasForeignKey("LovchaFantasy.Models.Rules", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("LovchaFantasy.Models.Game", b =>
                {
                    b.Navigation("Rules")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
